### ISSUE TITLE
Question: why fork appsignal/rdkafka-ruby?

### ISSUE THREAD

**Issue by carlost** [karafka/karafka-core#50]
The 2.0.9 change log mentioned:

> This change is needed to ensure that all consecutive releases are stable and compatible.

Can you share any other details about this decision?

- rdkafka hasn't even hit v1 status. have previous minor or patch point releases broken compatibility with karafka? 
- How are you verifying the behavior/performance of the fork against karafka & kafka in general? 
- Are you thinking about maintaining the fork in perpetuity or just until rdkafka hits 1.0?

Thanks for karafka, it has made working with kafka in ruby predictable and straightforward

**Comment by carlost** [comment]
> I can promise you that you will be satisfied :)

**Comment by mensfeld** [comment]
You are welcome. I will keep ppl posted. Usually I justify changes like this on our slack. Feel free to join. I will close this issue since I think I have answered all of your questions.
